services:
  js_mysql:
    container_name: js_mysql
    image: mysql:latest
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: pass_js
      TZ: Asia/Seoul
    ports:
#      - ${MYSQL_PORT}:${MYSQL_PORT}
      - 3307:3306