services:
  nginx:
    container_name: js_nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - js_bank_network

  backend:
    container_name: js_backend
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - js_bank_network
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: js_mysql
    image: mysql:latest
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - ${MYSQL_EXTERNAL_PORT}:${MYSQL_PORT}
    networks:
      - js_bank_network

  redis:
    container_name: js_redis
    image: "redis:alpine"
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_PORT}
    networks:
      - js_bank_network

networks:
  js_bank_network:
    driver: bridge